wandb_version: 1

num_epochs:
  desc: null
  value: 20
classifier:
  desc: null
  value:
    name: imagenet_classifier
    path: runs/classifiers/mixed10_pgd5_50_sgd_svgd1p
optimizer:
  desc: null
  value:
    module: torch.optim
    name: SGD
    args:
      lr: 0.1
      momentum: 0.9
      weight_decay: 0.0001
scheduler:
  desc: null
  value:
    type: cyclic
    args:
      lr_epochs:
      - 0
      - 1
      - 6
      - 12
      - 15
      - 20
      lr_values:
      - 0
      - 0.4
      - 0.04
      - 0.004
      - 0.0004
      - 0.0001
svgd:
  desc: null
  value:
    num_particles: 1
IS_ENSnP_or_SVGD1P_TRAINING:
  desc: null
  value: true
IS_IG_TRAINING:
  desc: null
  value: false
gpu:
  desc: null
  value:
    id: 0
pretrained:
  desc: null
  value:
    allowed: false
    path: ''
image_attack:
  desc: null
  value:
    module: advertorch.attacks
    name: PGDAttack
    args:
      eps: 0.0156862745
      eps_iter: 0.0039215686
      nb_iter: 5
      clip_min: -1.0
      clip_max: 1.0
latent_attack:
  desc: null
  value:
    module: advertorch.attacks
    name: PGDAttack
    args:
      eps: 0.02
      eps_iter: 0.005
      nb_iter: 5
      clip_min: null
      clip_max: null
dataset:
  desc: null
  value:
    name: mixed10
    num_classes: 10
    train:
      path: /home/revanth/on-off-manifold/stylegan2Ada_IS/dataset
      batch_size: 128
    test:
      path: /home/revanth/on-off-manifold/stylegan2Ada_IS/dataset
      batch_size: 256
whatsnew:
  desc: null
  value:
    default: Config is based on Previous Clean acc.
    content:
      '1': SVGD-1 PGD-5 attack with DMAT Budgets - Mixed10
distributed:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    code_path: code/prepare_classifiers_adv_dual_mix10_ours.py
    python_version: 3.9.18
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.37.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1708405760.100433
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.9.18
      5: 0.16.0
      6: 4.37.2
      8:
      - 5
      13: linux-x86_64
