num_epochs: 40
gpu_id: 0
seed: 0

classifier:
  name: imagenet_classifier
  path: runs/classifiers/single_networks/R50/Mix10/adv_models/

network:
  name: R50

optimizer:
  module: torch.optim
  name: Adam
  args:
    lr: 0.001

is_ig: False
lambda_ig: 1 # Need to test and find the best value

robustness_test: False

preprocessing: ["mean/std normalize", "flip/translation"]

image_attack:
  module: advertorch.attacks
  name: PGDAttack
  args:
    eps: 0.0156862745 # 4/255 as per paper, supplemental material
    eps_iter: 0.0039215686 # 1/255 as per paper, supplemental material
    nb_iter: 5
    clip_min: -1.0
    clip_max: 1.0

dataset:
  name: mixed10
  num_classes: 10
  train:
    path: /data/stylegan_old/dataset/imagenet
    batch_size: 64
  test:
    path: /data/stylegan_old/dataset/imagenet
    batch_size: 64

whatsHapenning: "Training a single network on Imagenet-10 with Adam optimizer - Adv training."