num_epochs: 20

classifier:
  name: imagenet_classifier
  path: runs/classifiers/mixed10_pgd5_50_sgd_svgd3p

optimizer:
  module: torch.optim
  name: SGD
  args:
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0001

scheduler:
  type: cyclic
  args:
    lr_epochs: !!python/tuple [0,1,6,12,15,20]
    lr_values: !!python/tuple [0,0.4,0.04,0.004,0.0004,0.0001]

svgd:
  num_particles: 3

IS_ENSnP_or_SVGD1P_TRAINING: False
IS_IG_TRAINING: False

gpu:
  id: 0

image_attack:
  module: advertorch.attacks
  name: PGDAttack
  args:
    eps: 0.0156862745 # 4/255 in [0, 1]
    eps_iter: 0.0039215686 # 1/255 in [0, 1]
    nb_iter: 5
    clip_min: -1.0
    clip_max: 1.0

latent_attack:
  module: advertorch.attacks
  name: PGDAttack
  args:
    eps: 0.02
    eps_iter: 0.005
    nb_iter: 5
    clip_min: null
    clip_max: null

dataset:
  name: mixed10
  num_classes: 10
  train:
    path: /home/revanth/on-off-manifold/stylegan2Ada_IS/dataset
    batch_size: 32
  test:
    path: /home/revanth/on-off-manifold/stylegan2Ada_IS/dataset
    batch_size: 32

whatsnew:
  default: "Config is based on Previous Clean acc."
  content: 
    "1": "SVGD-1 PGD-5 attack."